-- 000002_normalize_catalog.up.sql
-- PostgreSQL version

BEGIN;

CREATE TABLE book_authors (
    book_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,

    PRIMARY KEY (book_id, author_id),

    CONSTRAINT fk_book_authors_book
        FOREIGN KEY (book_id) REFERENCES books(id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT fk_book_authors_author
        FOREIGN KEY (author_id) REFERENCES authors(id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE INDEX idx_book_authors_author ON book_authors(author_id);

CREATE TABLE book_genres (
    book_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,

    PRIMARY KEY (book_id, genre_id),

    CONSTRAINT fk_book_genres_book
        FOREIGN KEY (book_id) REFERENCES books(id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT fk_book_genres_genre
        FOREIGN KEY (genre_id) REFERENCES genres(id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE INDEX idx_book_genres_genre ON book_genres(genre_id);

CREATE TABLE covers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL,
    variant VARCHAR(64) NOT NULL,
    url TEXT NOT NULL,
    mime_type VARCHAR(255) NULL,
    byte_size BIGINT NULL CHECK (byte_size >= 0),
    width INTEGER NULL CHECK (width >= 0),
    height INTEGER NULL CHECK (height >= 0),
    checksum_sha256 VARCHAR(64) NULL,

    CONSTRAINT uq_covers_book_variant UNIQUE (book_id, variant),
    CONSTRAINT fk_covers_book
        FOREIGN KEY (book_id) REFERENCES books(id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE INDEX idx_covers_book ON covers(book_id);

INSERT INTO book_authors (book_id, author_id)
SELECT id, book_author_id
FROM books
WHERE book_author_id IS NOT NULL;

INSERT INTO book_genres (book_id, genre_id)
SELECT id, book_genre_id
FROM books
WHERE book_genre_id IS NOT NULL;

-- A CHECK violation aborts this transaction if copying v0.1 relationships lost
-- or added a row. Avoid DO $$ blocks: golang-migrate's multi-statement parser
-- splits their internal semicolons before PostgreSQL can parse the block.
CREATE TEMPORARY TABLE catalog_migration_check (
    is_valid BOOLEAN NOT NULL CHECK (is_valid)
) ON COMMIT DROP;

INSERT INTO catalog_migration_check (is_valid)
SELECT
    (SELECT COUNT(*) FROM books WHERE book_author_id IS NOT NULL) =
    (SELECT COUNT(*) FROM book_authors)
    AND
    (SELECT COUNT(*) FROM books WHERE book_genre_id IS NOT NULL) =
    (SELECT COUNT(*) FROM book_genres);

DROP TABLE catalog_migration_check;

ALTER TABLE books
    DROP COLUMN book_author_id,
    DROP COLUMN book_genre_id;

COMMIT;
