version: "2"

run:
  go: "1.26"
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: false

output:
  formats:
    tab:
      path: stdout
      print-linter-name: true
  path-prefix: ""

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - sqlclosecheck
    - errcheck
    - errorlint
    - rowserrcheck
    - nilerr
    - nilnil
    - errname
    - depguard
  settings:
    staticcheck:
      checks:
        - all
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/LeeDark/book-social
            - github.com/a-h/templ
            - github.com/go-chi/chi/v5
            - github.com/lib/pq
            - maragu.dev/gomponents
            - modernc.org/sqlite
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
