package postgresql

import (
	"context"
	"database/sql"
	"os"
	"testing"

	"github.com/LeeDark/book-social/internal/modules/books"
)

func TestBookRepositoryListBooks(t *testing.T) {
	ctx := context.Background()
	db := newTestBookRepositoryDB(t, ctx)
	repo := NewBookRepository(db)

	gotBooks, err := repo.ListBooks(ctx)
	if err != nil {
		t.Fatalf("ListBooks() error = %v", err)
	}

	assertBookSlugs(t, gotBooks, []string{"emma", "frankenstein", "pride-and-prejudice", "the-time-machine"})
}

func TestBookRepositoryListBooksFiltered(t *testing.T) {
	ctx := context.Background()
	db := newTestBookRepositoryDB(t, ctx)
	repo := NewBookRepository(db)

	tests := []struct {
		name   string
		filter books.BookFilter
		want   []string
	}{
		{
			name:   "author slug",
			filter: books.BookFilter{AuthorSlug: "jane-austen"},
			want:   []string{"emma", "pride-and-prejudice"},
		},
		{
			name:   "genre slug",
			filter: books.BookFilter{GenreSlug: "science-fiction"},
			want:   []string{"frankenstein", "the-time-machine"},
		},
		{
			name:   "author and genre slug",
			filter: books.BookFilter{AuthorSlug: "mary-shelley", GenreSlug: "science-fiction"},
			want:   []string{"frankenstein"},
		},
		{
			name:   "unknown author slug",
			filter: books.BookFilter{AuthorSlug: "missing-author"},
			want:   []string{},
		},
		{
			name:   "unknown genre slug",
			filter: books.BookFilter{GenreSlug: "missing-genre"},
			want:   []string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotBooks, err := repo.ListBooksFiltered(ctx, tt.filter)
			if err != nil {
				t.Fatalf("ListBooksFiltered() error = %v", err)
			}

			assertBookSlugs(t, gotBooks, tt.want)
		})
	}
}

func TestBookRepositoryGetBookBySlug(t *testing.T) {
	ctx := context.Background()
	db := newTestBookRepositoryDB(t, ctx)
	repo := NewBookRepository(db)

	book, err := repo.GetBookBySlug(ctx, "frankenstein")
	if err != nil {
		t.Fatalf("GetBookBySlug() error = %v", err)
	}

	if book.Title != "Frankenstein" {
		t.Fatalf("Title = %q, want %q", book.Title, "Frankenstein")
	}
	if book.Author.Slug != "mary-shelley" {
		t.Fatalf("Author.Slug = %q, want %q", book.Author.Slug, "mary-shelley")
	}
	if book.Genre.Slug != "science-fiction" {
		t.Fatalf("Genre.Slug = %q, want %q", book.Genre.Slug, "science-fiction")
	}
}

func TestBookRepositoryGetBookBySlugReturnsNotFound(t *testing.T) {
	ctx := context.Background()
	db := newTestBookRepositoryDB(t, ctx)
	repo := NewBookRepository(db)

	_, err := repo.GetBookBySlug(ctx, "missing-book")
	if err != books.ErrBookNotFound {
		t.Fatalf("GetBookBySlug() error = %v, want %v", err, books.ErrBookNotFound)
	}
}

func TestBookRepositoryGetAuthorBySlug(t *testing.T) {
	ctx := context.Background()
	db := newTestBookRepositoryDB(t, ctx)
	repo := NewBookRepository(db)

	author, err := repo.GetAuthorBySlug(ctx, "mary-shelley")
	if err != nil {
		t.Fatalf("GetAuthorBySlug() error = %v", err)
	}

	if author.SurName != "Shelley" {
		t.Fatalf("SurName = %q, want %q", author.SurName, "Shelley")
	}
	if author.Slug != "mary-shelley" {
		t.Fatalf("Slug = %q, want %q", author.Slug, "mary-shelley")
	}
}

func TestBookRepositoryGetAuthorBySlugReturnsNotFound(t *testing.T) {
	ctx := context.Background()
	db := newTestBookRepositoryDB(t, ctx)
	repo := NewBookRepository(db)

	_, err := repo.GetAuthorBySlug(ctx, "missing-author")
	if err != books.ErrAuthorNotFound {
		t.Fatalf("GetAuthorBySlug() error = %v, want %v", err, books.ErrAuthorNotFound)
	}
}

func newTestBookRepositoryDB(t *testing.T, ctx context.Context) *sql.DB {
	t.Helper()

	dsn := os.Getenv("BOOK_SOCIAL_POSTGRES_TEST_DSN")
	if dsn == "" {
		t.Skip("set BOOK_SOCIAL_POSTGRES_TEST_DSN to run PostgreSQL repository tests")
	}

	db, err := Open(ctx, dsn)
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}
	t.Cleanup(func() {
		_ = db.Close()
	})

	statements := []string{
		`DROP SCHEMA IF EXISTS public CASCADE;`,
		`CREATE SCHEMA public;`,
		`CREATE TABLE authors (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			first_name VARCHAR(100) NOT NULL,
			second_name VARCHAR(100) NULL,
			sur_name VARCHAR(100) NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_authors_slug UNIQUE (slug)
		);`,
		`CREATE INDEX idx_authors_name ON authors(sur_name, first_name);`,
		`CREATE TABLE genres (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(120) NOT NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_genres_name UNIQUE (name),
			CONSTRAINT uq_genres_slug UNIQUE (slug)
		);`,
		`CREATE TABLE books (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(255) NOT NULL,
			slug VARCHAR(255) NOT NULL,
			description TEXT NULL,
			book_author_id INTEGER NULL,
			book_genre_id INTEGER NULL,
			CONSTRAINT uq_books_slug UNIQUE (slug),
			CONSTRAINT fk_books_author
				FOREIGN KEY (book_author_id) REFERENCES authors(id)
					ON UPDATE CASCADE
					ON DELETE SET NULL,
			CONSTRAINT fk_books_genre
				FOREIGN KEY (book_genre_id) REFERENCES genres(id)
					ON UPDATE CASCADE
					ON DELETE SET NULL
		);`,
		`CREATE INDEX idx_books_author ON books(book_author_id);`,
		`CREATE INDEX idx_books_genre ON books(book_genre_id);`,
		`INSERT INTO authors(id, first_name, second_name, sur_name, slug, description) VALUES
			(1, 'Jane', '', 'Austen', 'jane-austen', 'English novelist.'),
			(2, 'Mary', '', 'Shelley', 'mary-shelley', 'English writer.'),
			(3, 'H. G.', '', 'Wells', 'h-g-wells', 'English writer.');`,
		`INSERT INTO genres(id, name, slug, description) VALUES
			(1, 'Romance', 'romance', 'Love and relationships.'),
			(2, 'Science Fiction', 'science-fiction', 'Speculative fiction.');`,
		`INSERT INTO books(id, title, slug, description, book_author_id, book_genre_id) VALUES
			(1, 'Pride and Prejudice', 'pride-and-prejudice', 'A romance of manners.', 1, 1),
			(2, 'Emma', 'emma', 'A social comedy.', 1, 1),
			(3, 'Frankenstein', 'frankenstein', 'A created being.', 2, 2),
			(4, 'The Time Machine', 'the-time-machine', 'A journey into the future.', 3, 2);`,
	}

	for _, statement := range statements {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("exec test database statement: %v", err)
		}
	}

	return db
}

func assertBookSlugs(t *testing.T, bookList []books.Book, want []string) {
	t.Helper()

	got := make([]string, 0, len(bookList))
	for _, book := range bookList {
		got = append(got, book.Slug)
	}

	if len(got) != len(want) {
		t.Fatalf("book slugs = %v, want %v", got, want)
	}
	for i := range got {
		if got[i] != want[i] {
			t.Fatalf("book slugs = %v, want %v", got, want)
		}
	}
}
