-- schema_v0_1.sql
-- PostgreSQL version

-- Roles
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(64) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_roles_role_name UNIQUE (role_name)
);

-- Users
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    second_name   VARCHAR(100) NULL,
    sur_name      VARCHAR(100) NULL,
    login         VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email         VARCHAR(254) NOT NULL,
    user_role_id  INTEGER NOT NULL,

    CONSTRAINT uq_users_login UNIQUE (login),
    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT fk_users_role
       FOREIGN KEY (user_role_id) REFERENCES roles(id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT
);

CREATE INDEX idx_users_role ON users(user_role_id);

-- Authors
CREATE TABLE authors (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     first_name  VARCHAR(100) NOT NULL,
     second_name VARCHAR(100) NULL,
     sur_name    VARCHAR(100) NULL,
     slug VARCHAR(160) NOT NULL,
     description TEXT NULL,

     CONSTRAINT uq_authors_slug UNIQUE (slug)
);

CREATE INDEX idx_authors_name ON authors(sur_name, first_name);

-- Genres
CREATE TABLE genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    description TEXT NULL,

    CONSTRAINT uq_genres_name UNIQUE (name),
    CONSTRAINT uq_genres_slug UNIQUE (slug)
);

-- Books (v0.1: direct foreign keys to Author and Genre)
CREATE TABLE books (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       title VARCHAR(255) NOT NULL,
       slug VARCHAR(255) NOT NULL,
       description TEXT NULL,

       book_author_id INTEGER NULL,
       book_genre_id  INTEGER NULL,

       CONSTRAINT uq_books_slug UNIQUE (slug),

       CONSTRAINT fk_books_author
           FOREIGN KEY (book_author_id) REFERENCES authors(id)
               ON UPDATE CASCADE
               ON DELETE SET NULL,

       CONSTRAINT fk_books_genre
           FOREIGN KEY (book_genre_id) REFERENCES genres(id)
               ON UPDATE CASCADE
               ON DELETE SET NULL
);

CREATE INDEX idx_books_author ON books(book_author_id);
CREATE INDEX idx_books_genre  ON books(book_genre_id);

-- Cover: not decided yet (URL, blob, path, etc.).
-- If v0.1 needs one cover per book later, add a covers table with UNIQUE(book_id).

-- Shelves
CREATE TABLE shelves (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(120) NOT NULL,
     description TEXT NULL,

     CONSTRAINT uq_shelves_name UNIQUE (name)
);

-- Tags
CREATE TABLE tags (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(120) NOT NULL,
      description TEXT NULL,

      CONSTRAINT uq_tags_name UNIQUE (name)
);

-- Library (v0.1: shelf + book + optional tag)
CREATE TABLE library (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     library_shelf_id INTEGER NOT NULL,
     library_book_id  INTEGER NOT NULL,
     library_tag_id   INTEGER NULL,

     CONSTRAINT uq_library_shelf_book UNIQUE (library_shelf_id, library_book_id),

     CONSTRAINT fk_library_shelf
         FOREIGN KEY (library_shelf_id) REFERENCES shelves(id)
             ON UPDATE CASCADE
             ON DELETE RESTRICT,

     CONSTRAINT fk_library_book
         FOREIGN KEY (library_book_id) REFERENCES books(id)
             ON UPDATE CASCADE
             ON DELETE RESTRICT,

     CONSTRAINT fk_library_tag
         FOREIGN KEY (library_tag_id) REFERENCES tags(id)
             ON UPDATE CASCADE
             ON DELETE SET NULL
);

CREATE INDEX idx_library_shelf ON library(library_shelf_id);
CREATE INDEX idx_library_book  ON library(library_book_id);
CREATE INDEX idx_library_tag   ON library(library_tag_id);
