package testutil

import (
	"context"
	"database/sql"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

const PostgresTestDSNEnv = "BOOK_SOCIAL_POSTGRES_TEST_DSN"

func NewPostgresCatalogTestDB(t *testing.T, ctx context.Context) *sql.DB {
	t.Helper()

	dsn := os.Getenv(PostgresTestDSNEnv)
	if dsn == "" {
		t.Skipf("set %s to run PostgreSQL tests", PostgresTestDSNEnv)
	}

	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		t.Fatalf("db.PingContext() error = %v", err)
	}
	t.Cleanup(func() {
		_ = db.Close()
	})

	ResetPostgresPublicSchema(t, ctx, db)
	ApplyPostgresCatalogTestSchema(t, ctx, db)

	return db
}

func ResetPostgresPublicSchema(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()

	execStatements(t, ctx, db, []string{
		`DROP SCHEMA IF EXISTS public CASCADE;`,
		`CREATE SCHEMA public;`,
	})
}

func ApplyPostgresCatalogTestSchema(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()

	statements := []string{
		`CREATE TABLE authors (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			first_name VARCHAR(100) NOT NULL,
			second_name VARCHAR(100) NULL,
			sur_name VARCHAR(100) NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_authors_slug UNIQUE (slug)
		);`,
		`CREATE INDEX idx_authors_name ON authors(sur_name, first_name);`,
		`CREATE TABLE genres (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(120) NOT NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_genres_name UNIQUE (name),
			CONSTRAINT uq_genres_slug UNIQUE (slug)
		);`,
		`CREATE TABLE books (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(255) NOT NULL,
			slug VARCHAR(255) NOT NULL,
			description TEXT NULL,
			book_author_id INTEGER NULL,
			book_genre_id INTEGER NULL,
			CONSTRAINT uq_books_slug UNIQUE (slug),
			CONSTRAINT fk_books_author
				FOREIGN KEY (book_author_id) REFERENCES authors(id)
					ON UPDATE CASCADE
					ON DELETE SET NULL,
			CONSTRAINT fk_books_genre
				FOREIGN KEY (book_genre_id) REFERENCES genres(id)
					ON UPDATE CASCADE
					ON DELETE SET NULL
		);`,
		`CREATE INDEX idx_books_author ON books(book_author_id);`,
		`CREATE INDEX idx_books_genre ON books(book_genre_id);`,
	}

	execStatements(t, ctx, db, statements)
}
