package testutil

import (
	"context"
	"database/sql"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

const PostgresTestDSNEnv = "BOOK_SOCIAL_POSTGRES_TEST_DSN"

func NewPostgresCatalogTestDB(t *testing.T, ctx context.Context) *sql.DB {
	t.Helper()

	dsn := os.Getenv(PostgresTestDSNEnv)
	if dsn == "" {
		t.Skipf("set %s to run PostgreSQL tests", PostgresTestDSNEnv)
	}

	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		t.Fatalf("db.PingContext() error = %v", err)
	}
	t.Cleanup(func() {
		_ = db.Close()
	})

	ResetPostgresPublicSchema(t, ctx, db)
	ApplyPostgresCatalogTestSchema(t, ctx, db)

	return db
}

// NewPostgresCatalogV2TestDB creates the normalized catalog schema used by
// v0.2 migration and seed checks. The existing helper remains v0.1-compatible
// for repository tests until the v0.2.3 read-side changes land.
func NewPostgresCatalogV2TestDB(t *testing.T, ctx context.Context) *sql.DB {
	t.Helper()

	dsn := os.Getenv(PostgresTestDSNEnv)
	if dsn == "" {
		t.Skipf("set %s to run PostgreSQL tests", PostgresTestDSNEnv)
	}

	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		t.Fatalf("db.PingContext() error = %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	ResetPostgresPublicSchema(t, ctx, db)
	ApplyPostgresCatalogV2TestSchema(t, ctx, db)
	SeedPostgresCatalogV2TestData(t, ctx, db)

	return db
}

func ResetPostgresPublicSchema(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()

	execStatements(t, ctx, db, []string{
		`DROP SCHEMA IF EXISTS public CASCADE;`,
		`CREATE SCHEMA public;`,
	})
}

func ApplyPostgresCatalogTestSchema(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()

	statements := []string{
		`CREATE TABLE authors (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			first_name VARCHAR(100) NOT NULL,
			second_name VARCHAR(100) NULL,
			sur_name VARCHAR(100) NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_authors_slug UNIQUE (slug)
		);`,
		`CREATE INDEX idx_authors_name ON authors(sur_name, first_name);`,
		`CREATE TABLE genres (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(120) NOT NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_genres_name UNIQUE (name),
			CONSTRAINT uq_genres_slug UNIQUE (slug)
		);`,
		`CREATE TABLE books (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(255) NOT NULL,
			slug VARCHAR(255) NOT NULL,
			description TEXT NULL,
			book_author_id INTEGER NULL,
			book_genre_id INTEGER NULL,
			CONSTRAINT uq_books_slug UNIQUE (slug),
			CONSTRAINT fk_books_author
				FOREIGN KEY (book_author_id) REFERENCES authors(id)
					ON UPDATE CASCADE
					ON DELETE SET NULL,
			CONSTRAINT fk_books_genre
				FOREIGN KEY (book_genre_id) REFERENCES genres(id)
					ON UPDATE CASCADE
					ON DELETE SET NULL
		);`,
		`CREATE INDEX idx_books_author ON books(book_author_id);`,
		`CREATE INDEX idx_books_genre ON books(book_genre_id);`,
	}

	execStatements(t, ctx, db, statements)
}

func ApplyPostgresCatalogV2TestSchema(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()

	statements := []string{
		`CREATE TABLE authors (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			first_name VARCHAR(100) NOT NULL,
			second_name VARCHAR(100) NULL,
			sur_name VARCHAR(100) NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_authors_slug UNIQUE (slug)
		);`,
		`CREATE INDEX idx_authors_name ON authors(sur_name, first_name);`,
		`CREATE TABLE genres (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(120) NOT NULL,
			slug VARCHAR(160) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_genres_name UNIQUE (name),
			CONSTRAINT uq_genres_slug UNIQUE (slug)
		);`,
		`CREATE TABLE books (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(255) NOT NULL,
			slug VARCHAR(255) NOT NULL,
			description TEXT NULL,
			CONSTRAINT uq_books_slug UNIQUE (slug)
		);`,
		`CREATE TABLE book_authors (
			book_id INTEGER NOT NULL,
			author_id INTEGER NOT NULL,
			PRIMARY KEY (book_id, author_id),
			CONSTRAINT fk_book_authors_book
				FOREIGN KEY (book_id) REFERENCES books(id)
					ON UPDATE CASCADE ON DELETE CASCADE,
			CONSTRAINT fk_book_authors_author
				FOREIGN KEY (author_id) REFERENCES authors(id)
					ON UPDATE CASCADE ON DELETE CASCADE
		);`,
		`CREATE INDEX idx_book_authors_author ON book_authors(author_id);`,
		`CREATE TABLE book_genres (
			book_id INTEGER NOT NULL,
			genre_id INTEGER NOT NULL,
			PRIMARY KEY (book_id, genre_id),
			CONSTRAINT fk_book_genres_book
				FOREIGN KEY (book_id) REFERENCES books(id)
					ON UPDATE CASCADE ON DELETE CASCADE,
			CONSTRAINT fk_book_genres_genre
				FOREIGN KEY (genre_id) REFERENCES genres(id)
					ON UPDATE CASCADE ON DELETE CASCADE
		);`,
		`CREATE INDEX idx_book_genres_genre ON book_genres(genre_id);`,
		`CREATE TABLE covers (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			book_id INTEGER NOT NULL,
			variant VARCHAR(64) NOT NULL,
			url TEXT NOT NULL,
			mime_type VARCHAR(255) NULL,
			byte_size BIGINT NULL CHECK (byte_size >= 0),
			width INTEGER NULL CHECK (width >= 0),
			height INTEGER NULL CHECK (height >= 0),
			checksum_sha256 VARCHAR(64) NULL,
			CONSTRAINT uq_covers_book_variant UNIQUE (book_id, variant),
			CONSTRAINT fk_covers_book
				FOREIGN KEY (book_id) REFERENCES books(id)
					ON UPDATE CASCADE ON DELETE CASCADE
		);`,
		`CREATE INDEX idx_covers_book ON covers(book_id);`,
	}

	execStatements(t, ctx, db, statements)
}

func SeedPostgresCatalogV2TestData(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()

	statements := []string{
		`INSERT INTO authors(id, first_name, second_name, sur_name, slug, description) VALUES
			(1, 'Jane', '', 'Austen', 'jane-austen', 'English novelist.'),
			(2, 'Bram', '', 'Stoker', 'bram-stoker', 'Irish writer.'),
			(3, 'Mary', '', 'Shelley', 'mary-shelley', 'English writer.');`,
		`INSERT INTO genres(id, name, slug, description) VALUES
			(1, 'Classic', 'classic', 'Enduring literature.'),
			(2, 'Horror', 'horror', 'Fiction intended to unsettle.');`,
		`INSERT INTO books(id, title, slug, description) VALUES
			(1, 'Pride and Prejudice', 'pride-and-prejudice', 'A novel of manners.'),
			(2, 'Dracula', 'dracula', 'A gothic horror novel.');`,
		`INSERT INTO book_authors(book_id, author_id) VALUES
			(1, 1), (1, 3), (2, 2);`,
		`INSERT INTO book_genres(book_id, genre_id) VALUES
			(1, 1), (2, 2);`,
		`INSERT INTO covers(book_id, variant, url, mime_type, width, height) VALUES
			(1, 'front', 'https://example.test/covers/pride-and-prejudice.jpg', 'image/jpeg', 600, 900);`,
	}

	execStatements(t, ctx, db, statements)
}
